### ISSUE TITLE
The GGIRCS carbon tax calculator should only consider one of the flaring gases (CO2 being the default choice) 

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-ggircs#263]
See the comment here: https://miro.com/app/board/o9J_kk1Bxv0=/?openComment=3074457350671252191

We are potentially counting flared natural gas thrice, which would lead in an increased CT amount
This needs to be fixed in the GGIRCS carbon tax calculator

See comments in YT: GGIRCS-2105

**Comment by matthieu-foucault** [comment]
added as a checklist item of #353
