### ISSUE TITLE
Explore reusable UI toolkit

### ISSUE THREAD

**Issue by Maralsotoudehnia** [bcgov/cas-ggircs#265]
AC
~~Not using react bootstrap~~
~~Potential constraints (developers to elaborate)~~
~~Reach out to BC Design System team about contributing (what's the process?)~~
- [x] the cas-ggircs repo uses the service-development-toolkit from button with  a BCGOV theme
- [x] open issues in the service development toolkit for `Popover` `ListGroup` and `react-bootstrap-typeahead` functionality support
- [x] fix tests

Reference links
https://github.com/button-inc/service-development-toolkit

**Comment by pbastia** [comment]
From the previous discussions:
- Taking full advantage of the reusable toolkit means implementing SSR (server-side rendering)

There are components we use in our applications that don't have (yet?) an equivalent:
- `Form`
- `Typeahead` from react-bootstrap-typeahead
- `List` and `ListGroup`
- `Alerts`
- `Table`
... and more.
These can for the most part be implemented in raw HTML/css

**Comment by Maralsotoudehnia** [comment]
@pbastia Any suggestion about how to review this, if at all?

**Comment by pbastia** [comment]
@Maralsotoudehnia log in to cas-ggircs dev: https://cas-ggircs-dev.apps.silver.devops.gov.bc.ca
Make sure that all functionality is there (basically just the file browser) - you'll notice little changes of style related to the toolkit change

**Comment by Maralsotoudehnia** [comment]
Looks great @pbastia. Nice work!
