### ISSUE TITLE
remove unused columns from ggircs_portal.facility/organisation tables

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ggircs#271]
The following table columns are unused & should be removed.

facility...
      report_id
      swrs_report_id
      swrs_organisation_id

organisation...
      report_id
      swrs_report_id
      reporting_year
      operator_trade_name
      duns
      operator_mailing_address
      operator_city
      operator_province
      operator_postal_code
      operator_country

import_swrs_organisation_facility needs to stop importing / inserting these columns.

comment from YT: create_application_mutation_chain() uses facility.report_id and will need refactoring

**Comment by dleard** [comment]
unnecessary effort. closing
