### ISSUE TITLE
CE Needs - Discovery Phase

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ggircs#272]
CAS's Compliance and Enforcement team requires a simpler way to compare BCGHG_StatusReport Excel Sheets when submitted data seems awry.   from submitted Two main priorities are easier file comparison and more effect search of compressed files.  

With goals established, SD and UX will follow the research steps outlined in the GDX Service Design Playbook found [here](https://bcgov.github.io/design-research-guide/planning-research/).

**Internal Prep**
- [x] Compile a list of questions and unknowns with the GGIRCS team to be clarified in discovery phase
- [x] Set up a[ Miro space](https://miro.com/app/board/o9J_l6FlMbE=/) to track research findings and stakeholders

**The Context**
- [x] Evaluate the Compliance SME's process document to see how this problem fits into the team's big-picture process
- [x] Create a stakeholder map to understand who is involved and/or affected

**Role Shadowing / Conversations with C&E Team**
- [x] Via the Compliance SME and users listed below, set up dates and times for unmoderated shadowing to understand business workflows
- [x] Record sessions and archive in [C&E Research and Design folder](https://teams.microsoft.com/_#/files/Compliance%20Internal%20Users?threadId=19%3A0c9a7e9492574975840bdd9a6ca41d87%40thread.tacv2&ctx=channel&context=C%2526E%2520Research%2520and%2520Design&rootfolder=%252Fteams%252F00608-ComplianceInternalUsers%252FShared%2520Documents%252FCompliance%2520Internal%2520Users%252FC%2526E%2520Research%2520and%2520Design) in Teams. 

(see [Design phase ticket, 277](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/277))

Additional notes:
Use the Compliance Internal Users MS Teams channel for setup/discussions as needed. The list of internal users and contacts can be found in the above MS Teams channel wiki.
[Here is the link](https://bcgov.sharepoint.com/teams/00608-ScrumTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={3823A232-E8A5-4EEB-816A-12D919BA1684}) to the business context info (meeting notes from June 30 meeting).

**Comment by rajpersram** [comment]
Jaimie and Raj to break down into smaller components regarding SD, UX-R, UX-D

**Comment by Dianadec** [comment]
Questions for research: Do they want to input the Report ID or a similar file search to what they already have?

**Comment by rajpersram** [comment]
(Wed, July 7) Left message with John Nagle to get in touch to arrange shadowing times with at least 3 participants to better understand their current workflow and needs.

**Comment by LindsayMacfarlane** [comment]
Thank you Jamie for walking me through all the activities that have been done to date for the C&E discovery phase. I'm so excited to learn more about this business area and how we can support them.
