### ISSUE TITLE
CE Needs: Design Phase

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ggircs#277]
After determining outcomes from research phase from [ticket 272](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/272), implement design steps to improve C&E's workflow for comparing Status Report Excel sheet to identify oddities in submitted data. 

Feedback and testing with CE team will occur throughout steps.

**Design Tasks**
- [ ] Idea generation on potential solutions
- [ ] Lo-fi mockup
- [ ] Hi-fi mockup with detailed interaction states
- [ ] Guidance around using new solution

#### Acceptance Criteria

- [ ] Provide mockups for potential solutions (via Figma or Miro)
- [ ] Improved means for file comparison  
- [ ] More effective search methods of compressed files  
- [ ] Quickly identify dissimilar reports for a given Operator

#### Additional context

Background info and nice-to-haves listed in [meeting notes, found here](https://bcgov.sharepoint.com/teams/00608-ScrumTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={3823A232-E8A5-4EEB-816A-12D919BA1684}).

**Comment by jaimiebutton** [comment]
This ticket is no longer relevant as there is little UX/UI needed for this stage of the process. Closing the ticket :)
