### ISSUE TITLE
As a compliance officer, I can see which GHG reports have a Verification Statement requirement in Metabase

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ggircs#283]
## Description
According to [GGERR, Division 2](https://www.bclaws.gov.bc.ca/civix/document/id/lc/statreg/249_2015#division_d1e3540) (C&E team to confirm the source), reporting operations must submit a 3rd party verification statement if they meet certain emission thresholds in the current or past three years of reporting (also called the 3 Year Rule). 

AC:
- Allow users to see whether or not a GHG Report is required to have a verification statement

## Implementation details
The following approach would be a possible way to implement this in metabase:

1. create a question returning, for each report, the sum of CO2e, excluding the following records from the emission table: 
    * gas_type = CO2bioC
    * unit_name = `CoalMiningPitMines`
    * activity_name = `MobileCombustion`

1. If the total emissions of a report is >=25,000t, then there is a verification requirement for the 3 consecutive periods following, i.e.: Given a report from the `2019` reporting period, when the total emissions is >=25,000 tonnes of CO2e, then the `vs_requirement_until` column should have a value of `2022`

1. Aggregate the previous results per SWRS facility id, and return the maximum value for the `vs_requirement_until` column

1. for each report where `vs_requirement_until` is >= 2020, create a question that returns the following:
    * company name
    * swrs facility id
    * facility name
    * facility type
    * primary naics
    * total emissions and report numbers for the 2017 to 2020 reporting periods (create a question per reporting period to easily join)
    * 2020 report has a verification statement
    * ~link to 2020 verification statement~ (will add once #288)

When validating the results against the compliance spreadsheet, the following needs to be checked (might need a meeting with John et al.):

> Ensure that emissions in the report are not double counted when GHG report includes subprocess_name: Additional information for cement and lime production facilities only (not aggregated in totals); Additional information required when other activities selected are Activities in tablee 2 rows 2,4,5, or 6. Note, i am not sure if this is a quirk of Qinghan's extractions, or if this is something that MB would need to filter - this is just how we filter it using his extractions.

**Comment by johnnagle** [comment]
A reporting operation (LFO, SFO or EIO) is required to submit a GHG report with a verification statement if:

- The reporting operation (LFO, SFO or EIO) has emissions greater than or equal to 25,000 tCO2e, not including "reporting-only" emissions, in a reporting period

-  "reporting-only emissions" means carbon dioxide from biomass listed in [Schedule C](https://www.bclaws.gov.bc.ca/civix/document/id/lc/statreg/249_2015#ScheduleC) and emissions from source types listed in items 2 and 25 of Table 1 of [Schedule A](https://www.bclaws.gov.bc.ca/civix/document/id/lc/statreg/249_2015#ScheduleA);

- For an LFO, assess compliance on the LFO reported total and not the sum of the individual facilities (IF_a, IF_b, L_c) to avoid double counting. If a discrepancy exists between the sum of the individual facilities and the LFO total, flag for further review - this may be an issue if one total is below the threshold and one is above the threshold.

- Ensure that emissions in the report are not double counted when GHG report includes subprocess_name: Additional information for cement and lime production facilities only (not aggregated in totals); Additional information required when other activities selected are Activities in tablee 2 rows 2,4,5, or 6. Note, i am not sure if this is a quirk of Qinghan's extractions, or if this is something that MB would need to filter - this is just how we filter it using his extractions.

- If a reporting operation has emissions greater than or equal to 25,000 tCO2e, not including "reporting-only" emissions, in a reporting period it therefore has a verification requirement for the 3 consecutive reporting periods following

- A reporting operation has a verification requirement if the Director under GGIRCA imposed it (discretionary requirement)

**Comment by johnnagle** [comment]
In the verification review spreadsheet that we shared, please refer to the tab "Emissions_Total Attr" to note how we are filtering the data

**Comment by Dianadec** [comment]
This card needs to be updated so that all devs know what the rules are in MB (note from July 27 mtg)

**Comment by johnnagle** [comment]
@Dianadec Sorry i might be confused - anything i need to update?

**Comment by Dianadec** [comment]
@johnnagle Nope sorry for any confusion - that was a note for devs :)

**Comment by matthieu-foucault** [comment]
The LFO compliance part was moved to #289
This needs a dev (likely @dleard or me) to find how the rules listed by John above are represented in our `swrs` schema.

**Comment by matthieu-foucault** [comment]
@naomiaro @dleard @pbastia Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/283?planning-poker)

**Comment by LindsayMacfarlane** [comment]
Thank you for the demo @matthieu-foucault !
