### ISSUE TITLE
As a compliance officer, I want to see discrepancies between emissions of individual facilities and their parent facility, so that I can further review them

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ggircs#289]
#### Description:

LFO facilities are comprised of individual facilities (IF_a, IF_b, L_c). Both the LFO and individual facilities are reported in SWRS, but discrepancies might exist. 

If a discrepancy exists between the sum of the individual facilities and the LFO total, flag for further review - this may be an issue if one total is below the threshold and one is above the threshold.

When looking for discrepancies, the data can be aggregated at the following levels:
 - total facility emissions
 - process (Activity Name)
 - subprocess (Sub Activity Name)
 - emission type
 - gas type

AC
- [ ] Given that I am loading the "LFO vs individual facilities emissions total" question, when an LFO has total CO2e emissions that do not match the sum of CO2e emission of its individual facilities, then the corresponding row is highlighted in red.
- [ ] Given that I am loading the "LFO vs individual facilities emissions by Process" question, when an LFO's Activity has total CO2e emissions that do not match the sum of CO2e emission of its individual facilities for the same Process, then the corresponding row is highlighted in red.
- [ ] Given that I am loading the "LFO vs individual facilities emissions by Sub Process" question, when an LFO's Sub Activity has total CO2e emissions that do not match the sum of CO2e emission of its individual facilities for the same Sub Process, then the corresponding row is highlighted in red.
- [ ] Given that I am loading the "LFO vs individual facilities emissions by Emission Type" question, when an LFO's Emission Type has total CO2e emissions that do not match the sum of CO2e emission of its individual facilities for the same Emission Type, then the corresponding row is highlighted in red.
- [ ] Given that I am loading the "LFO vs individual facilities emissions by Gas Type" question, when an LFO's Gas Type has total CO2e emissions that do not match the sum of CO2e emission of its individual facilities for the same Gas Type, then the corresponding row is highlighted in red.
- [ ] Given that I am loading the "LFO vs individual facilities emissions" dashboard, when entering a reporting year, business name, and/or LFO facility name, the five questions above are filtered accordingly

**Comment by johnnagle** [comment]
Hi @matthieu-foucault. It would probably be helpful to be able to see a breakdown of the emissions as this would allow you to see where the discrepancy is. A couple of things to note - right now I think Qinghan undertakes this analysis of discrepancies between an LFO and the sum of its individual facilities annually using PowerBI and it would be a good idea to consider how we can support that work through MetaBase going forward nad wat you are describing sounds like it might do that. The issue as framed is really about determining the obligation to obtain verification in relation to the threshold (25,000 tonnes, not including reporting only emissions) - but when a discrepancy exists, we are then wanting to locate the reason for the discrepancy and then query whether the discrepancy is resulting from a non-compliance (or whatever the reason). Once we resolve that secondary question, we can then answer completely the first question of whether they met the threshold and were required to have a verification statement. The second thing I would note is that we are reviewing the threshold where verification would be required, and its possible in the future that the threshold would have different gas type or activity type inclusion or exclusion rules (e.g. 25,000 tonnes, excluding Biomass from Schedule C but including mobile and ). Important that we may be able to change those parameters.

**Comment by Dianadec** [comment]
CE to respond to the question in this card once their team reviews it once they are back from vacation (I believe this week).

**Comment by johnnagle** [comment]
@Dianadec hi, let me know if i missed a question but response above

**Comment by Dianadec** [comment]
Thanks @johnnagle ! All good. ZenHub didn't post my message from earlier as it was having github issues. I just deleted my message since i see your response now.

**Comment by dleard** [comment]
To be assessed on the final version of a report

**Comment by Dianadec** [comment]
I'll follow up with QB about how he uses power BI

**Comment by Dianadec** [comment]
Meeting setup with QB for Aug 24

**Comment by dleard** [comment]
work has been paused until the meeting with QB

**Comment by LindsayMacfarlane** [comment]
Considering ticket complete based on acceptance criteria. Although there is a lot of back and forth at the moment with business area, tickets can be created to address those comments/feedback.
