### ISSUE TITLE
As a compliance officer, I can see the md5 hash of every attachment, so that I can determine if 2 attachments are identical or not

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ggircs#290]
## Description 

Within this issue, we need to 
 - [x] add a file_md5 column in the `swrs_history.attachment` table created in #266
 - [x] create a script that downloads any attachment that does not have a `file_md5`, calculates its md5 hash, and sets it in the database
 - [x] add the script at the end of the SWRS ECCC DAGs

**Comment by LindsayMacfarlane** [comment]
Thank you for the demo @matthieu-foucault ! Approved on my end :)
