### ISSUE TITLE
CE Retros & Feedback Loops

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#342]
While we wrap up our work with compliance, it will be helpful to set up feedback loops to have the GGIRCS team and CE team reflect together on the new solutions developed. 

**Acceptance Criteria:**
- [x] Decide on check-in approach
- [x] Reach out to CE Team to set up conversation 
- [x] Schedule session
- [x] Design session in the C&E Thinkspace Miro board

**Comment by matthieu-foucault** [comment]
@jaimiebutton should we check in with the C&E team soon?

**Comment by jaimiebutton** [comment]
Good call @matthieu-foucault! Pulling into this sprint's backlog.

**Comment by LindsayMacfarlane** [comment]
Excellent session @jaimiebutton I appreciate your passion and commitment to finding fun ways to be bring our teams together and to keep the line of communication open.
