### ISSUE TITLE
Audit SWRS Schema for unused tables and views

### ISSUE THREAD

**Issue by naomiaro** [bcgov/cas-ggircs#349]
## Description

Through discussion with Qinghan, I've noticed there might be a potential issue with duplicate data in our view "Report With Org".

Not sure about the usage of this view/table.

![Screenshot 2021-09-27 at 10.42.41 AM.png](https://images.zenhubusercontent.com/60ca41b0e24126871585d0a5/a6d5eb5d-7f6f-4431-8eb3-25e801804a6b)

This is probably an issue with multiple views or tables that are either unnecessary or already flagged as "deprecated"
Those tables/views can be hidden in the metabase configuration. 
Auditing which tables/views are used by existing questions can be done in the test environment, by hiding tables and using the questions check script to detect if hiding a table/view triggers an error.

**Comment by dleard** [comment]
Done as part of #404
