### ISSUE TITLE
As a metabase user I can see the estimated carbon tax in the SWRS schema

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-ggircs#353]
### Description 

The reporting and analytics needs to estimate the carbon tax paid by reporting operation, in order to allow the province to define budgets, or to respond to information requests from other units.

The `swrs` schema has  a `carbon_tax_calculation` view which was developed two years ago, but suffered from known performance issues. In addition to the performance issues, known issues related to the accuracy of the tax estimates exist in the calculator, and it should be re-written.

### Features to implement (to be refined)
- [x] The Calculator should **exclude LFO** facilities from the results (display IF_a, IF_b and L_c instead)
- [x] An `emission_category` table, similar to the one used in CIIP, should exist, and indicate which emission categories are taxed (the waste should carbon-taxed, same as in CIIP)
- [x] A `taxed_venting_emission_type` table should exist, listing the venting emission types that are taxed
- [x] Missing indices (if any) should be added and the `carbon_tax_calculation` view should be rewritten to remain performant
- [x] Given that a reporting operation reported a **flared** CO2 gas amount of X tonnes of CO2e,
  when the carbon tax calculator is executed,
  then it should return a record with a Natural gas fuel amount of Y (as per WCI.20 EF for non-marketable gas, Table 20-3: 2.151 kgCO2/m3 non-marketable NG in BC - *this reference must be in the view comment*)
- [x] Given that a reporting operation reported a **vented** gas amount of X tonnes of CH4,
  when the carbon tax calculator is executed,
  then it should return a record with a Natural gas fuel amount of Y (as per WCI.353 Calculation of Greenhouse Gas Emissions, Equations 350-9 & 360-20 0.6785 kgCH4/m3- *this reference must be in the view comment*)

#### Notes
- RT will be starting holidays on Dec 10 and may be away until May 2022. Scoping of work may want to be completed sooner. 
- Keep ES in the loop

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/353?planning-poker) with ZenHub @matthieu-foucault @dleard @AlexZorkin
