### ISSUE TITLE
Plan for capturing R&A process

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#373]
The GGIRCS team will soon be working with R&A to document their process of receiving & processing data from SWRS.

Acceptance Criteria:
- [x] Create rough plan of attack for capturing process
- [x] Review plan and get feedback from CF and ES
- [x] Ideate potential types of maps (Service Blueprint vs. Business Process Map vs. System Model) using work done in the Mapping the System Miro board

Notes:
- Keep CF/ES and team up-to-date on progress and outcomes

**Comment by LindsayMacfarlane** [comment]
Thank you for putting time and thought into how you want to approach this work @jaimiebutton. I'm super excited for next steps to support Public Reporting.
