### ISSUE TITLE
Metabase alerts for fuel - emission_category assumptions

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ggircs#383]
*These alerts cannot be created until the latest cas-ggircs release has been deployed to production*

The swrs carbon tax calculator makes some assumptions about the data ingested from swrs. These assumptions need to be validated via metabase alerts to let us know if there is a change.

Assumptions:
A fuel is only ever associated to one emission category
A fuel is never reported without an associated emission category

These assumptions are currently true for all data received beyond the 2011 reporting year.

#### Acceptance Criteria

- [x] add a metabase alert: Fuel has > 1 emission_category
- [x] add a metabase alert: Fuel has a fuel_amount and no emission_category (year > 2011)
(these may end up being one alert)

**Comment by matthieu-foucault** [comment]
Looks good to me. For those alerts (we have one for new fuels as well), perhaps we should create functions/views that run the sql command, so that we can test them with pgTap
