### ISSUE TITLE
Compile C&E Next Steps

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#390]
Following the [C&E Retrospective](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/342) on January 14th, this ticket documents the capturing of next steps identified.

- [x] Create list of next steps identified
- [x] Pass list to Lindsay for feedback/additions
- [x] Schedule tickets for requested adjustments in ZenHub
- [x] Make a plan to schedule another retrospective when C&E team has used the tool more (captured in [this ticket](https://github.com/bcgov/cas-ggircs/issues/399))

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton. Perhaps not for the checklist, but other considerations: support program area on business case, identify in 2022-23 branch plan.

**Comment by LindsayMacfarlane** [comment]
Loved the icebreaker/warm-up game. I always appreciate these team building exercises and regular check-ins to make sure we are all on the same page. It was also a great opportunity as we were able to identify unknown bugs during our conversation. Great work @jaimiebutton !
