### ISSUE TITLE
Compile BCCR Recommendations

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#391]
Following the call with the BC Carbon Registry team leads on January 14th, this ticket documents the capturing of recommendations for service design & user research.

- [x] Create list of recommendations identified
- [x] Pass list to Lindsay for feedback/additions
- [x] Pass list on to BCCR team leads

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton - looks good to me :)

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @jaimiebutton. A future step would be take this and theme/group the feedback to create a more standard document (as we've been working towards on Miro). These are great questions that I think we would get most program areas to consider when requesting a digital service.
