### ISSUE TITLE
C&E - Change Threshold Calculation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#405]
#### Description:

Note from John:

"The verification obligation check right now looks at the last 4 years of reporting and checks if an operation emits more than 25,000 tCO2e not including Biomass from Schedule C, emissions from mobile combustion, and fugitive coal methane.

We recently passed an OIC that has changed this threshold to 25,000 tCO2e, not including Biomass from Schedule C. As a result, for the 2021 reporting period the threshold is different and needs to be factored in to the query that GGIRCS developed for us. We would hope to have this fixed up before the May 31 reporting deadline if possible.

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault! I've moved it to the top of the backlog. Are you able to provide more details around the development checklist?
