### ISSUE TITLE
Mapping System Changes

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#410]
- [x] Conduct research into how to map the impacts of policy changes on people, systems and processes
- [x] Consider how to show current, short-term, and long-term future changes
- [x] Share system map from Agile Org Design Miro board
- [x] Pass findings back to Hanna in 'Mapping Policy Changes' Miro board

**Comment by LindsayMacfarlane** [comment]
Looks amazing @jaimiebutton - you obviously put a lot of thought and consideration into how this could be approached. I see a lot of value in the transformation mapping. Some additional thoughts/consideration:

- I wonder if med term should also be considered in terms timelines. In govt we often break change into short, med, and long term.
- At what point would a prioritization matrix fit into this process? This might also help dig into those short/med/long term timelines and goals.
-  As Hanna digs into this further, it would also be helpful to know what system changes are priority and even what systems. It would also be good to understand the level of granularity we are hoping for and when the team could be engaged to provide input.
