### ISSUE TITLE
Set up Intro to Miro for R&A Team

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-ggircs#417]
This ticket captures the work done for an 'Intro to Miro' session with the R&A Team, using a spreadsheet from a current project as example of how to put Miro in action.

- [x] Look at spreadsheet sent over by Emilie
- [x] Design session to see birds-eye-view of spreadsheet in Miro
- [x] Create 'Intro to Miro' frame for future use

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - can you clarify, is this issue simply setting up Miro with training...or will it also capture holding a session/workshop?

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, we do have a session set up with Emilie to do a quick intro to Miro's capabilities but this ticket just captures the setting up of a session & reusable intro to Miro frame

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - this ticket looks complete, can it be moved to the PO Review column? Also, thank you for taking the time to walk me through what you did and how you've been supporting ES.

**Comment by jaimiebutton** [comment]
Hey, yes I think I did that at the same time you wrote this comment 😅

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton ! I've also set up a follow up with ES to share my experiences with reg amendments.

**Comment by jaimiebutton** [comment]
🙌
