### ISSUE TITLE
As a CAS user, I want to define the charges associated with each fuel defined in the Carbon Tax Act

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ggircs#431]
Description:

CAS users should be able to add/edit the fuel charges for each CTA fuel via a UI. This would be changing data in the ggircs_parameters.fuel_charge table. The UI for this can re-use some aspects of the un-mapped fuels component.

Acceptance Criteria:

Given I am logged in to the ggircs app
When I am on the landing page
Then I can navigate to a CTA management page
And I can see a selectable list of the CTA fuels on the left side of the screen

Given I am in the CTA management UI
When I select a CTA fuel type
Then I can see the related fuel charges and tax periods for that fuel

Given I am in the CTA management UI
When I need to add a fuel charge for an upcoming reporting year
Then I can add fuel charge data for that year

Given I am in the CTA management UI
When I need to edit a fuel charge 
Then I can edit fuel charge data

Development Checklist:

* [x] user can navigate to a CTA management page
* [x] fuel charge data can be edited
* [x] new fuel charge data can be added (ie: for upcoming reporting years)
* [x] dates cannot overlap when adding/editing rate periods

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/431?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard! I appreciate the instructions :) Perhaps I don't have the needed permissions as I'm not able to select (or see) any fuel types in order to edit/create rate periods (see screenshot). 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/d1944b55-f335-4acc-a3ae-26371a02e2f5)

**Comment by dleard** [comment]
Ah, yes that's because of the issue here in #430, which could really be a bug rather than tech debt I suppose. The permissions are not in sync with the database being dropped in dev. I cycled the pod and you should be able to see fuels now.

**Comment by LindsayMacfarlane** [comment]
Perfect - thank you! Tested in dev by:
- Updated period end date for Aviation fuel
- Added a new rate period for Coke Oven Gas (got expected error message if there was an overlap in period dates); able to add a new rate period.

This was really intuitive to use!

Meets acceptance criteria. Thanks for all your work on this one @dleard
