### ISSUE TITLE
Fix ECCC download failure from April 13

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ggircs#503]
The cas-ggircs-eccc dag that downloads the emission reports from swrs failed on April 13th because of a bad file upload.
We'll need to remove the invalid 1.4kb partial file from our GCS bucket and the corresponding data in our ECCC tables in swrs_extract and then manually run the dag again to ensure we've properly downloaded the new swrs dump.

Results of exploration:
- Since Jan 20th, authenticating to the SWRS ftp has been periodically failing in 2 places where auth is required: wget-spider and upload.js
- Going back 6 months of logs, this failure never happened before Jan 20th
- After Jan 20th, the number of daily authentication failures by month are { Jan: 6, Feb: 13, March: 16 }
- We believe this is an external issue with the ftp itself
- We're reaching out to file a bug with eccc
- Our code could be made more resilient to handle these random auth failures & retry those auth points until we get a good response to try and mitigate the issue

Todo:
- [This](https://github.com/bcgov/cas-ggircs/blob/develop/eccc/upload/app/upload.js#L74) (url) => arrow function should be made `async`
- [This](https://github.com/bcgov/cas-ggircs/blob/develop/eccc/upload/app/upload.js#L45) fetch call should be retried until it comes back with a 200 status or fail after 20 tries
- [This](https://github.com/bcgov/cas-ggircs/blob/develop/eccc/upload/app/init.sh#L14) call to wget-spider should be retried until it comes back non-zero or fail after 20 tries

**Comment by pbastia** [comment]
I can see the retries in the upload task. Thanks @dleard
