### ISSUE TITLE
As an analyst I want to see a calculated quantity for emissions using AR5 GWP values so that I can compare older years values with the updated GWP

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-ggircs#516]
A new column in the swrs.emission table is required to allow analysts to see what the calculated quantity for previous years would be according to the [updated AR5 GWP values ](https://www2.gov.bc.ca/assets/gov/environment/climate-change/ind/reporting-emissions/2023/ggrica_bulletin_025.pdf).

As an analyst
When I am querying the swrs.emission data in Metabase
I can see an AR5 calculated quantity value which is calculated by quantity x gwp(AR5 value)

Development steps:
- add a GWP table to the `swrs_parameters` schema with the updated AR5 GWP values
- The GWP table should have all `gas_type` values in the `emission` table (can be found in metabase). This is how we will join emissions to gwp
- Each `gas_type` row should have an associated AR5 GWP value
- add a numeric column to the swrs.emission table `ar5_calculated_quantity`
- in the load function for swrs.emission, use the `quantity` value from emission and the GWP value from the GWP table (by joining on emission.gas_type = gwp.gas_type) to calculate the `ar5_calculated_quantity` column

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ggircs/516?planning-poker) with Zenhub @BCerki @gurjmatharu @JoshLarouche @sam-warren @Sepehr-Sobhani

**Comment by pbastia** [comment]
@dleard  the `ar5_calculated_quantity` column is null in Metabase-dev, when the quantity is filled out. I also can't see a `swrs_parameters` schema in the swrs database

**Comment by dleard** [comment]
@BCerki @pbastia The dev data is entirely synthetic, created with inserts rather than parsed via the ETL (where the ar5 calculation is done) so the calculated field will always be empty in dev. The pgTap tests covered the load() function and passed, I suggest deploying this to test where I believe the ETL does run over a few reports and the value should show up there.

**Comment by pbastia** [comment]
Aaaah thanks for clarifying. I thought we had fake XML that got parsed.
Seems like we can't test in dev then
