### ISSUE TITLE
Tech Debt: Remove dependency on Terraform Cloud and cas-shelf

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-ggircs#540]
We are spinning down Terraform Cloud. Follow the patterns established in _cas-registration_ and _cas-ciff_ for migration and running terraform as an OpenShift Job.

## Acceptance Criteria

- [x] Migrate Terraform resources from Terraform Cloud to a state held in a Google Cloud Storage bucket (these will have been created by _cas-pipeline_. 
- [x] Create Terraform modules for resources
- [x] Create Helm template to import modules and run Terraform job

**Comment by patriciarussellCAS** [comment]
I'm approving based on assumptions that this wouldn't be in the Pending PO Approval pipeline if there were any issues  :)
